#!/bin/bash
apt update -y && apt install -y firefox gnome-core tightvncserver curl gnupg2 iptables 
echo -e "password\npassword" | vncpasswd
tightvncserver :1
echo "function vncstart {
    tightvncserver :1
}"> ~/.bashrc.
